[package]
name = "DeepFilterDataLoader"
version = "0.1.12-pre"
authors = ["Hendrik Schr√∂ter <h.schroeter@pm.me>"]
edition = "2021"

[lib]
name = "libdfdata"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
deep_filter = { features = [
  "dataset",
  "vorbis",
  "flac",
  "cache",
  "dataset_timings",
], path = "../libDF" }
pyo3 = { version = "^0.16", default_features = true, features = [
  "extension-module",
] }
log = { version = "0.4", features = ["std"] }
crossbeam-channel = "^0.5"
numpy = "^0.16"
ndarray = "^0.15"
