[package]
name = "DeepFilterDataLoader"
version = "0.1.9"
authors = ["Hendrik SchrÃ¶ter <h.schroeter@pm.me>"]
edition = "2021"

[lib]
name = "libdfdata"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
deep_filter = { path = "../libDF", features = ["dataset"] }
pyo3 = { version = "^0.15", default_features = true, features = ["extension-module"]}
numpy = "^0.15"
ndarray = "^0.15"
