[package]
name = "DeepFilterDataLoader"
version = "0.2.6-pre"
authors = ["Hendrik Schr√∂ter"]
edition = "2021"

[lib]
name = "libdfdata"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
deep_filter = { features = ["dataset", "vorbis", "flac"], path = "../libDF" }
pyo3 = { version = "^0.17", default_features = true, features = [
  "extension-module",
] }
log = { version = "0.4", features = ["std"] }
crossbeam-channel = "^0.5"
numpy = "^0.17"
ndarray = "^0.15"
