[package]
name = "DeepFilterDataLoader"
version = "0.1.11"
authors = ["Hendrik SchrÃ¶ter <h.schroeter@pm.me>"]
edition = "2021"

[lib]
name = "libdfdata"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
deep_filter = { features = ["dataset"], version = "0.1.11" }
pyo3 = { version = "^0.16", default_features = true, features = ["extension-module"]}
crossbeam-channel = "^0.5"
numpy = "^0.16"
ndarray = "^0.15"
