[package]
name = "DeepFilterDataLoader"
version = "0.1.11-pre"
authors = ["Hendrik SchrÃ¶ter <h.schroeter@pm.me>"]
edition = "2021"

[lib]
name = "libdfdata"
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
default = []

[dependencies]
deep_filter = { features = ["dataset", "vorbis", "flac"], path = "../libDF" }
pyo3 = { version = "^0.16", default_features = true, features = ["extension-module"]}
numpy = "^0.16"
ndarray = "^0.15"
