[workspace]
resolver = "2"

members = [
  "libDF",
  "pyDF",
  "pyDF-data",
  "ladspa",
]

[profile.dev]
opt-level = 1
incremental = false
lto = false

[profile.release]
debug = false
opt-level = 3
lto = "thin"

[profile.release-lto]
inherits = "release"
debug = false
lto = "fat"
strip = true
